@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Menu : new Menu(List<String>,boolean,int X,int Y)
Main -> Menu : getImage()
Menu -> VueMenue : New VueMenue(this)
Menu -> Main : VueMenue
Main -> VueMenue : Update()
VueMenue -> Menu : getOrientation()
Menu -> VueMenue : Boolean orientation
VueMenue -> Menu : getElements()
Menu -> VueMenue : List<String> elements
VueMenue -> Menu : getX()
Menu -> VueMenue : int x
VueMenue -> Menu : getY()
Menu -> VueMenue : int y
VueMenue -> VueMenue : getChildren().add(Pane bordure)

@enduml