@startuml
'https://plantuml.com/sequence-diagram

abstract Instance{
    +Instance(
    +getMethode() : List<Composante>
    +getAttribut() : List<Composante>
    +toString() : abstract String
}

class Classe{
    +Classe()
}

class Interface{
    +Interface()
}

abstract Composante{
    -type : String
    +getType() : String
}

class Methode{
    +getModelisation() : VueInstance
    +getSquelette() : String
}

class Attribut{
    +getModelisation() : VueInstance
    +getSquelette() : String
}

class Import{
    -nom : String
    +getNom() : String
}

class Modele{
    -repertoire : File
    +Modele(String source)
    -creationInstance() : void
    -creationRelation() : void
    +getInstance(String name) : Instance
    +toString() : String
}

interface Relation{
    -classeSrc : String
    -classeCible : String
    +toString() : String
}

class Heritage{
    +Heritage()
    +toString() : String
}

class Implementation{
    +Implementation()
    +toString() : String
}

class Association {
    -nbSrc : String
    -nbCible : String
    +Association()
    +toString() : String
}

abstract globale{
    -nom : String
    -acces : String
    -modifier : List<String>
    -Visible : Boolean
    +isVisible() : Boolean
    +getNom() : String
    +getAcces() : String
    +getModifier() : List<String>
}


Instance--|>globale
Composante--|>globale
Modele "1" -> "*" Instance  : -classeInit
Instance "1" -> "*" Composante : -attribut
Instance "1" -> "*" Composante : -Methode
Instance "1" --> "*" Import : -import
Classe --|> Instance
Interface --|> Instance
Methode --|> Composante
Attribut --|> Composante
Modele "1" ----> "*"  Relation : -Relation
Association ..|> Relation
Heritage ..|> Relation
Implementation ..|> Relation

@enduml