@startuml
'https://plantuml.com/sequence-diagram

autonumber

Modele -> Classe: Classe(Class)
activate Classe
Classe -> Class: getName()
activate Class
Class --> Classe:String
deactivate Class
Classe -> Class:getDeclaredFields()
activate Class
Class --> Classe:Field[]
deactivate Class
loop
Classe -> Field:getName()
activate Field
Field --> Classe:String
deactivate Field
Classe -> Field:getModifiers()
activate Field
Field --> Classe:int
deactivate Field
Classe -> Attribut: Attribut(String nom, String type)
end
Classe -> Class:getDeclaredMethods()
activate Class
Class --> Classe:Method[]
deactivate Class
loop
Classe -> Method:getName()
activate Method
Method --> Classe:String
deactivate Method
Classe -> Method:getModifiers()
activate Method
Method --> Classe:int
deactivate Method
Classe -> Methode: Methode(String nom, String type)
end

@enduml