@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant Modele
participant Instance
participant Composant



 Main -> Modele: Modele(String cheminRepertoire)

loop Instance instance : List<Fichier>
alt NomFichier se finit avec ".java"
Modele->Modele:creationInstance(String cheminRepertoire)
alt Si attribut
loop
Instance->Composant:attribut()
else  methode
Instance->Composant:methode()
end
end
end
@enduml